import threading
from AudioTranscriber import AudioTranscriber
import customtkinter as ctk
import AudioRecorder
import time
import subprocess
import os
import ctypes
from dotenv import load_dotenv
from LLMClient import LLMClient
from backend.StealthOverlay import StealthOverlayManager
import keyboard
from datetime import datetime

# Windows API constants for stealth mode
WDA_EXCLUDEFROMCAPTURE = 0x00000011
GWL_EXSTYLE = -20
WS_EX_APPWINDOW = 0x00040000
WS_EX_TOOLWINDOW = 0x00000080

# Global flags for tracking generation and visibility status
is_generating = False
is_hidden = False
main_window = None
overlay_mgr = None
transcriber_global = None  # For hotkey access

def save_interview_log(transcriber):
    """
    Save the current interview transcript to a markdown file in interviews/ directory.
    Format: Speaker questions with clean markdown headers.
    """
    try:
        # Create interviews directory if it doesn't exist
        if not os.path.exists("interviews"):
            os.makedirs("interviews")
            print("[INFO] Created interviews/ directory")

        # Generate timestamp filename
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"interviews/interview_{timestamp}.md"

        # Get transcript data
        transcript = transcriber.get_transcript()

        if not transcript or len(transcript.strip()) < 10:
            print("[INFO] No transcript data to save")
            return None

        # Format as markdown with clean headers
        markdown_content = f"""# Interview Session - {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

## Transcript

{transcript}

---
*Generated by AI Copilot Pro*
"""

        # Write to file
        with open(filename, "w", encoding="utf-8") as f:
            f.write(markdown_content)

        print(f"[INFO] Interview log saved: {filename}")
        return filename

    except Exception as e:
        print(f"[ERROR] Failed to save interview log: {e}")
        return None

def toggle_app_visibility():
    """
    Global hotkey handler (Ctrl+Shift+H) to hide/show all application windows.
    Uses root.after() for thread-safety with Tkinter.
    """
    global is_hidden, main_window, overlay_mgr

    def _toggle():
        global is_hidden

        if is_hidden:
            # Restore windows
            if main_window:
                main_window.deiconify()
            if overlay_mgr and overlay_mgr.overlay:
                overlay_mgr.overlay.show_overlay()
            is_hidden = False
            print("[INFO] Application windows RESTORED (Ctrl+Shift+H)")
        else:
            # Hide windows
            if main_window:
                main_window.withdraw()
            if overlay_mgr and overlay_mgr.overlay:
                overlay_mgr.overlay.hide_overlay()
            is_hidden = True
            print("[INFO] Application windows HIDDEN (Ctrl+Shift+H)")

    # Execute in Tkinter's main thread for safety
    if main_window:
        main_window.after(0, _toggle)

def hotkey_clear_session():
    """
    Global hotkey handler (Ctrl+Shift+C) to clear session and save log.
    Saves transcript, clears data, resets LLM, and clears UI.
    """
    global main_window, transcriber_global, overlay_mgr

    def _clear():
        if transcriber_global:
            print("[INFO] Hotkey triggered: Clearing session (Ctrl+Shift+C)")

            # Save interview log before clearing
            save_interview_log(transcriber_global)

            # Clear transcript data
            transcriber_global.clear_transcript_data()

            # Clear overlay cards
            if overlay_mgr and overlay_mgr.overlay:
                try:
                    for widget in overlay_mgr.overlay.cards_container.winfo_children():
                        widget.destroy()
                except:
                    pass

    if main_window:
        main_window.after(0, _clear)

def panic_button():
    """
    Emergency exit hotkey (Ctrl+Alt+End) - instantly kills the application.
    No cleanup, no saving, immediate termination.
    """
    print("[PANIC] Emergency exit triggered (Ctrl+Alt+End)")
    os._exit(0)

def apply_total_stealth(window):
    """
    Apply complete stealth mode to the main window:
    1. Hide from screen capture (Zoom, Teams, OBS)
    2. Hide from Windows Taskbar
    3. Hide from Alt+Tab menu
    """
    try:
        window.update()
        hwnd = ctypes.windll.user32.GetParent(window.winfo_id())

        if hwnd:
            # 1. Exclude from screen capture
            result = ctypes.windll.user32.SetWindowDisplayAffinity(hwnd, WDA_EXCLUDEFROMCAPTURE)
            if result:
                print("[INFO] Main window excluded from screen capture")
            else:
                print("[WARNING] Failed to exclude main window from screen capture")

            # 2. Hide from Taskbar and Alt+Tab
            ex_style = ctypes.windll.user32.GetWindowLongW(hwnd, GWL_EXSTYLE)
            new_style = (ex_style & ~WS_EX_APPWINDOW) | WS_EX_TOOLWINDOW
            ctypes.windll.user32.SetWindowLongW(hwnd, GWL_EXSTYLE, new_style)

            # Force window to update its style
            window.withdraw()
            window.deiconify()

            print("[INFO] Main window hidden from Taskbar and Alt+Tab")
        else:
            print("[WARNING] Could not get window handle for stealth mode")

    except Exception as e:
        print(f"[ERROR] Failed to apply total stealth: {e}")

def write_in_textbox(textbox, text):
    textbox.delete("0.0", "end")
    textbox.insert("0.0", text)

def update_transcript_UI(transcriber, transcript_textbox, suggestion_textbox, llm_client, overlay_manager, status_indicator):
    global is_generating

    # Update status indicators in real-time
    speaker_status = transcriber.get_statuses()
    status_indicator.configure(text=f"{speaker_status} Speaker")

    # Update transcript
    transcript_string = transcriber.get_transcript()
    write_in_textbox(transcript_textbox, transcript_string)

    latest_speaker_text = transcriber.get_latest_speaker_text()
    if latest_speaker_text and len(latest_speaker_text.strip()) > 20:
        if not hasattr(update_transcript_UI, 'last_processed') or update_transcript_UI.last_processed != latest_speaker_text:

            if not is_generating:
                update_transcript_UI.last_processed = latest_speaker_text
                is_generating = True

                def thread_target():
                    global is_generating
                    try:
                        get_ai_suggestion(latest_speaker_text, suggestion_textbox, llm_client, overlay_manager)
                    finally:
                        is_generating = False

                threading.Thread(target=thread_target, daemon=True).start()

    transcript_textbox.after(300, update_transcript_UI, transcriber, transcript_textbox, suggestion_textbox, llm_client, overlay_manager, status_indicator)

def get_ai_suggestion(interviewer_question, suggestion_textbox, llm_client, overlay_manager):
    try:
        suggestion_textbox.delete("0.0", "end")
        suggestion_textbox.insert("0.0", "🤔 Analyzing question...\n")

        full_response = ""
        response_generator = llm_client.get_suggestion(interviewer_question)

        # Create a new Q&A card in the overlay
        answer_box = overlay_manager.overlay.add_qa_card(interviewer_question)

        # Clear "Thinking..." message
        answer_box.configure(state="normal")
        answer_box.delete("0.0", "end")
        answer_box.configure(state="disabled")

        # Stream tokens to both dashboard and overlay card
        for token in response_generator:
            full_response += token

            # Update dashboard
            suggestion_textbox.delete("0.0", "end")
            suggestion_textbox.insert("0.0", full_response)
            suggestion_textbox.update()

            # Stream to overlay card
            answer_box.configure(state="normal")
            answer_box.insert("end", token)
            answer_box.see("end")
            answer_box.configure(state="disabled")
            answer_box.update()

    except Exception as e:
        print(f"[ERROR] Failed to get AI suggestion: {e}")
        suggestion_textbox.delete("0.0", "end")
        suggestion_textbox.insert("0.0", "❌ AI suggestion failed")

        # Update overlay card if it exists
        if 'answer_box' in locals():
            answer_box.configure(state="normal")
            answer_box.delete("0.0", "end")
            answer_box.insert("0.0", "❌ AI suggestion failed")
            answer_box.configure(state="disabled")

def clear_context(transcriber, suggestion_textbox, llm_client, overlay_manager):
    # Save interview log before clearing
    save_interview_log(transcriber)

    transcriber.clear_transcript_data()

    suggestion_textbox.delete("0.0", "end")
    suggestion_textbox.insert("0.0", "Ready for next question...")
    llm_client.reset_conversation()

    # Clear all cards in overlay
    if overlay_manager.overlay:
        for widget in overlay_manager.overlay.cards_container.winfo_children():
            widget.destroy()

    if hasattr(update_transcript_UI, 'last_processed'):
        delattr(update_transcript_UI, 'last_processed')

def create_ui_components(root, transcriber, llm_client, overlay_manager):
    root.title("AI Ecoute")
    root.geometry("1600x900")

    # Premium color palette
    bg_dark = "#0F172A"
    sidebar_bg = "#1E293B"
    card_bg = "#1E293B"
    accent_blue = "#38BDF8"
    accent_purple = "#A78BFA"
    text_primary = "#F8FAFC"
    text_secondary = "#CBD5E1"
    text_muted = "#94A3B8"
    border_color = "#334155"

    root.configure(fg_color=bg_dark)

    # Grid layout: left panel (transcript) + right panel (AI suggestions)
    root.grid_columnconfigure(0, weight=3)
    root.grid_columnconfigure(1, weight=2)
    root.grid_rowconfigure(0, weight=1)

    # Premium typography
    title_font = ("Segoe UI", 22, "bold")
    content_font = ("Segoe UI", 16)
    status_font = ("Segoe UI", 13)
    button_font = ("Segoe UI", 15, "bold")

    # ========== LEFT PANEL: Live Transcript ==========
    left_panel = ctk.CTkFrame(root, fg_color=card_bg, corner_radius=0)
    left_panel.grid(row=0, column=0, sticky="nsew", padx=(0, 1), pady=0)
    left_panel.grid_columnconfigure(0, weight=1)
    left_panel.grid_rowconfigure(2, weight=1)

    # Header with title and status indicators
    header_container = ctk.CTkFrame(left_panel, fg_color="transparent")
    header_container.grid(row=0, column=0, sticky="ew", padx=35, pady=(30, 5))
    header_container.grid_columnconfigure(1, weight=1)

    transcript_title = ctk.CTkLabel(
        header_container,
        text="📝 Live Transcript",
        font=title_font,
        text_color=text_primary,
        anchor="w"
    )
    transcript_title.grid(row=0, column=0, sticky="w")

    # Status indicator with visual dots
    status_indicator = ctk.CTkLabel(
        header_container,
        text="⚪ Speaker",
        font=status_font,
        text_color=text_muted,
        anchor="e"
    )
    status_indicator.grid(row=0, column=1, sticky="e", padx=(10, 0))

    # Subtitle
    subtitle_label = ctk.CTkLabel(
        left_panel,
        text="Real-time conversation transcription",
        font=("Segoe UI", 13),
        text_color=text_muted,
        anchor="w"
    )
    subtitle_label.grid(row=1, column=0, sticky="w", padx=35, pady=(5, 20))

    # Transcript textbox - clean, spacious design
    transcript_textbox = ctk.CTkTextbox(
        left_panel,
        font=content_font,
        text_color=text_secondary,
        fg_color=bg_dark,
        border_width=0,
        corner_radius=0,
        wrap="word",
        spacing1=8,
        spacing3=8
    )
    transcript_textbox.grid(row=2, column=0, sticky="nsew", padx=35, pady=(0, 20))

    # Pause/Resume button - NEW FEATURE
    pause_button = ctk.CTkButton(
        left_panel,
        text="⏸️ Pause AI Listening",
        font=button_font,
        height=50,
        corner_radius=10,
        fg_color="#EF4444",
        hover_color="#DC2626",
        text_color=text_primary,
        command=lambda: toggle_pause(transcriber, pause_button)
    )
    pause_button.grid(row=3, column=0, sticky="ew", padx=35, pady=(0, 10))

    # Clear button with subtle styling
    clear_button = ctk.CTkButton(
        left_panel,
        text="Clear Session",
        font=button_font,
        height=50,
        corner_radius=10,
        fg_color=border_color,
        hover_color="#475569",
        text_color=text_primary,
        command=lambda: clear_context(transcriber, None, llm_client, overlay_manager)
    )
    clear_button.grid(row=4, column=0, sticky="ew", padx=35, pady=(0, 30))

    # ========== RIGHT PANEL: AI Copilot ==========
    right_panel = ctk.CTkFrame(root, fg_color=card_bg, corner_radius=0)
    right_panel.grid(row=0, column=1, sticky="nsew", padx=0, pady=0)
    right_panel.grid_columnconfigure(0, weight=1)
    right_panel.grid_rowconfigure(2, weight=1)

    # AI Copilot header with gradient-style accent
    ai_header_container = ctk.CTkFrame(right_panel, fg_color="transparent")
    ai_header_container.grid(row=0, column=0, sticky="ew", padx=35, pady=(30, 5))

    ai_title = ctk.CTkLabel(
        ai_header_container,
        text="💡Ecoute",
        font=title_font,
        text_color=accent_blue,
        anchor="w"
    )
    ai_title.grid(row=0, column=0, sticky="w")

    # AI subtitle
    ai_subtitle = ctk.CTkLabel(
        right_panel,
        text="Instant talking points powered by local LLM",
        font=("Segoe UI", 13),
        text_color=text_muted,
        anchor="w"
    )
    ai_subtitle.grid(row=1, column=0, sticky="w", padx=35, pady=(5, 20))

    # AI suggestion textbox - prominent, high-contrast
    suggestion_textbox = ctk.CTkTextbox(
        right_panel,
        font=("Segoe UI", 17),
        text_color=accent_blue,
        fg_color=bg_dark,
        border_width=0,
        corner_radius=0,
        wrap="word",
        spacing1=10,
        spacing3=10
    )
    suggestion_textbox.grid(row=2, column=0, sticky="nsew", padx=35, pady=(0, 20))
    suggestion_textbox.insert("0.0", "Waiting for interviewer's question...")

    # Toggle overlay button - vibrant accent
    toggle_overlay_button = ctk.CTkButton(
        right_panel,
        text="Toggle Stealth Overlay",
        font=button_font,
        height=50,
        corner_radius=10,
        fg_color="#2563EB",
        hover_color="#1D4ED8",
        text_color=text_primary,
        command=overlay_manager.toggle_visibility
    )
    toggle_overlay_button.grid(row=3, column=0, sticky="ew", padx=35, pady=(0, 30))

    # Fix clear button lambda
    clear_button.configure(command=lambda: clear_context(transcriber, suggestion_textbox, llm_client, overlay_manager))

    return transcript_textbox, suggestion_textbox, status_indicator

def toggle_pause(transcriber, pause_button):
    """Toggle pause state and update button appearance"""
    is_paused = transcriber.toggle_pause()

    if is_paused:
        pause_button.configure(
            text="▶️ Resume AI Listening",
            fg_color="#10B981",
            hover_color="#059669"
        )
    else:
        pause_button.configure(
            text="⏸️ Pause AI Listening",
            fg_color="#EF4444",
            hover_color="#DC2626"
        )

def main():
    global main_window, overlay_mgr, transcriber_global

    load_dotenv()

    # Create interviews directory on startup
    if not os.path.exists("interviews"):
        os.makedirs("interviews")
        print("[INFO] Created interviews/ directory for logs")

    speaker_device_index = os.getenv("SPEAKER_DEVICE_INDEX")

    if speaker_device_index:
        speaker_device_index = int(speaker_device_index)
    else:
        speaker_device_index = None

    context_file = "temp_context.txt"
    if os.path.exists(context_file):
        with open(context_file, "r", encoding="utf-8") as f:
            interview_context = f.read()
            print(f"[INFO] Loaded interview context ({len(interview_context)} characters)")
    else:
        interview_context = ""
        print("[INFO] No interview context found")

    # Load AI persona from environment
    ai_persona = os.getenv("AI_PERSONA", "Short Bullets")
    print(f"[INFO] AI Persona: {ai_persona}")

    try:
        llm_client = LLMClient(provider="local", persona=ai_persona)
        print("[INFO] LLM client initialized successfully")
    except Exception as e:
        print(f"[ERROR] Failed to initialize LLM client: {e}")
        print("[WARNING] Continuing without AI suggestions")
        llm_client = None

    root = ctk.CTk()
    main_window = root  # Store reference for global hotkey

    # Apply total stealth mode to main window
    apply_total_stealth(root)

    def cleanup_on_exit():
        print("[INFO] Cleaning up and saving interview log...")
        try:
            # Save interview log before exit
            if transcriber_global:
                save_interview_log(transcriber_global)

            if os.path.exists("temp_context.txt"):
                os.remove("temp_context.txt")
                print("[INFO] Removed temp_context.txt")
        except Exception as e:
            print(f"[WARNING] Failed to cleanup: {e}")

    def hard_exit():
        print("[INFO] Application closing...")
        cleanup_on_exit()
        try:
            if transcriber_global:
                transcriber_global.close()
        except:
            pass
        if main_window:
            main_window.quit()
            main_window.destroy()

    overlay_manager = StealthOverlayManager()
    overlay_mgr = overlay_manager  # Store reference for global hotkey
    overlay_manager.create_overlay()
    print("[INFO] Stealth overlay created")

    # Register global hotkeys in a daemon thread to avoid blocking
    def register_hotkeys():
        try:
            keyboard.add_hotkey('ctrl+shift+h', toggle_app_visibility)
            print("[INFO] Global hotkey registered: Ctrl+Shift+H to toggle visibility")

            keyboard.add_hotkey('ctrl+shift+c', hotkey_clear_session)
            print("[INFO] Global hotkey registered: Ctrl+Shift+C to clear session")

            keyboard.add_hotkey('ctrl+alt+end', panic_button)
            print("[INFO] Global hotkey registered: Ctrl+Alt+End for emergency exit")
        except Exception as e:
            print(f"[WARNING] Failed to register global hotkeys: {e}")
            print("[WARNING] Hotkeys require administrator privileges on Windows")

    # Register hotkeys in background thread
    hotkey_thread = threading.Thread(target=register_hotkeys, daemon=True)
    hotkey_thread.start()

    try:
        speaker_recorder = AudioRecorder.DefaultSpeakerRecorder(device_index=speaker_device_index)

        transcriber = AudioTranscriber(speaker_recorder)
        transcriber_global = transcriber  # Store for hotkey access
        transcriber.start()

        root.protocol("WM_DELETE_WINDOW", hard_exit)

        transcript_textbox, suggestion_textbox, status_indicator = create_ui_components(root, transcriber, llm_client, overlay_manager)

        print("READY")

        if llm_client:
            update_transcript_UI(transcriber, transcript_textbox, suggestion_textbox, llm_client, overlay_manager, status_indicator)
        else:
            def update_transcript_no_llm():
                transcript_string = transcriber.get_transcript()
                write_in_textbox(transcript_textbox, transcript_string)
                transcript_textbox.after(300, update_transcript_no_llm)
            update_transcript_no_llm()

        root.mainloop()

    except Exception as e:
        print(f"[ERROR] Failed to initialize audio system: {e}")

        root.protocol("WM_DELETE_WINDOW", lambda: (cleanup_on_exit(), root.quit(), root.destroy()))

        transcript_textbox, suggestion_textbox, status_indicator = create_ui_components(root, None, llm_client, overlay_manager)

        error_message = f"❌ Audio Initialization Failed\n\n{str(e)}\n\nPossible causes:\n• Invalid audio device selected\n• Audio device disconnected\n• Sample rate not supported\n\nPlease restart and select different audio devices."
        write_in_textbox(transcript_textbox, error_message)
        write_in_textbox(suggestion_textbox, "Audio system unavailable")

        root.mainloop()

if __name__ == "__main__":
    main()
